"""increase article_quantity precision to numeric(14,2)

Revision ID: 9d8a3aa781d0
Revises: 003_increase_company_document
Create Date: 2026-06-14 05:46:25.450615+00:00

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "9d8a3aa781d0"
down_revision: str | Sequence[str] | None = "003_increase_company_document"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "adjudications",
        "article_quantity",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=14, scale=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "adjudications",
        "article_quantity",
        existing_type=sa.Numeric(precision=14, scale=2),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
